name: Bump Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  autobump:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Tap formulae
        run: |
          brew tap sean01zhang/formulae
      - name: Bump packages
        uses: Homebrew/actions/bump-packages@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          casks: >
            sean01zhang/formulae/window-switcher
          fork: false
